// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pimndhbsrbsffltsldcx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpbW5kaGJzcmJzZmZsdHNsZGN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1NDM3NDcsImV4cCI6MjA3NTExOTc0N30.OAf0GyMTfXhRF00gXqCrceHSmOV6evx4olWV27fgOVM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});